Implemented the clickable text or "hotspots" for the output log. I've added the option to pass an option ({hotspot, SubString}) into both log:message/2 and log:error/2 containing a substring of the given message which is the portion of the message to to style as a clickable hotspot. When a hotspot is clicked the hotspot text is extracted and compared to a list of hard-coded keywords (currently "output" is the only one, but more can be added), and an appropriate action is taken. The only action at the moment is to switch from the log to the output window when the user clicks on "output" in the compiler error log message:
19:26:21  ERROR: Compilation failed arith.erl. See output.

A function has been added to ide (display_output_window/1) to allow switching between the output windows. Currently this is passed an atom (log, output), although I might decide to move the window id macro definitions into the header file (from ide) and use these instead.

Also added the "Export" sub-menu to the menu.